// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Movie is an autogenerated mock type for the Movie type
type Movie struct {
	mock.Mock
}

// AskMovie provides a mock function with given fields: moviename
func (_m *Movie) AskMovie(moviename string) ([]byte, error) {
	ret := _m.Called(moviename)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(moviename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(moviename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
